apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: smackapi
spec:
  hosts:
    - smackapi
  http:
  - route:
    - destination:
        host: smackapi
        subset: "{{.Values.prodLabel}}"
      weight: {{.Values.prodWeight}}
    - destination:
        host: smackapi
        subset: "{{.Values.canaryLabel}}"
      weight: {{.Values.canaryWeight}}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: smackapi
spec:
  host: smackapi
  subsets:
  - name: prod
    labels:
      version: prod
  - name: new
    labels:
      version: new
