apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: brigade-brigade
    chart: brigade-0.14.0
    heritage: Tiller
    release: brigade
  name: brigade-brigade-github-gw
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
