apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smackapi-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smackapi
        version: prod
    spec:
      containers:
      - name: smackapi
        image: a2ito/smackapi:latest
        #image: chzbrgr71/smackapi:latest
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: acrregistrykey
