---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - image: gcr.io/kaniko-project/executor:latest
      args:
      - --dockerfile=kube-con-2017-ito/smackapi/Dockerfile
      - --context=git://github.com/a2-ito/istio-and-brigade-demo.git
      - --destination={{.Values.api.image}}:{{.Values.api.imageTag}}
      - --cache=false
      - --build-arg=IMAGE_TAG_REF={{.Values.api.imageTag}}
      name: kaniko
      volumeMounts:
        - name: kaniko-secret
          mountPath: /secret
      env:
        - name: DOCKER_CONFIG
          value: /secret/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: .docker/config.json
